image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Running unit tests"
    - python -m unittest discover -s tests

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t api-service .

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - apt-get update && apt-get install -y ansible  # Install Ansible
    - ansible-playbook ansible-playbook/deploy.yml
