global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_service'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'metrics_service'
    static_configs:
      - targets: ['localhost:5001']
